# Generated by Django 5.1.1 on 2024-10-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('banner', models.ImageField(upload_to='Media/Products')),
                ('title', models.TextField()),
                ('descriptions', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('color', models.TextField()),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=500, unique=True)),
            ],
        ),
    ]
