# Generated by Django 5.1.1 on 2024-10-01 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
