# Generated by Django 5.1.1 on 2024-10-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_product_sales_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('author', models.CharField(max_length=100)),
                ('categories', models.CharField(max_length=200)),
                ('comments_count', models.IntegerField(default=0)),
            ],
        ),
    ]
