# Generated by Django 5.1.1 on 2024-10-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='banner',
            field=models.ImageField(default='0', upload_to='media/blogs'),
        ),
    ]
