# Generated by Django 5.1.1 on 2024-10-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
