# Generated by Django 5.1.1 on 2024-10-15 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='added_at',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
