# Generated by Django 5.1.1 on 2024-10-26 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='product',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='Home.product'),
            preserve_default=False,
        ),
    ]
